### ISSUE TITLE
Memory leak when calling var_to_bytes with arrays

### ISSUE THREAD

**Issue by zealot35** [Daylily-Zeleen/GUS-Godot-Universal-Serializer-2.0#5]
## Describe the Issue
When calling var_to_bytes() and passing an array, memory usage slowly goes up.
This doesn't seem to happen with other types.
I tested packed arrays too, and the issue persists

## Provide an Example
Start a new project in 4.2, create a node, attach the following code to it, hit run and view the static memory debug monitor

```py
extends Node

var _thing : Array
var _pack : PackedByteArray

func _physics_process(delta):
	_thing = [Vector3(7.256, -2.01, 5.734), 125612, 3511, 6543012, Vector2(21.67, 7.45)]
	for i in 100:
		_pack = GUS.var_to_bytes(_thing)
```

The memory usage goes up roughly 0.5-1 mb per second.

Here is a picture of the debug monitor showing the above results:

![image](https://github.com/user-attachments/assets/1ce9783d-d9b9-4f5b-b7ab-9a8b20a049fb)

There appears to be no memory leak when decoding arrays with bytes_to_var(), as shown below:

![image](https://github.com/user-attachments/assets/108def01-43e1-41a4-9fe2-a0d16222de4f)

**Comment by Daylily-Zeleen** [comment]
This is due to the bug of godot-cpp.
Already fixed by [updating godot-cpp](https://github.com/Daylily-Zeleen/GUS-Godot-Universal-Serializer-2.0/commit/a8c396742cf978185463b4c7b148fbbe43d7beda).


Please download the [latest plugin (v2.1.8)](https://github.com/Daylily-Zeleen/GUS-Godot-Universal-Serializer-2.0/releases/tag/v2.1.8) to test.

**Comment by zealot35** [comment]
Bug confirmed fixed after updating! Thank you! I'll leave this closed now.
